
name: mirror

on: push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: cc332030/git-mirror-action@github
        timeout-minutes: 30
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          COMMAND: |
            ${{ secrets.SSH }} \
            ${{ secrets.GRADLE_PUBLISH_COMMAND }} \
            ${{ secrets.REPOSITORY }} \
            ${{ secrets.BRANCH }}
