
name: publish

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: init gnupg
        run: ${{ secrets.INIT_GPG }}
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
      - name: init gradle
        run: ${{ secrets.INIT_GRADLE }}
        env:
          GPG_SIGN_KEY: ${{ secrets.GPG_SIGN_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.USER }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      - uses: actions/cache@v2
        with:
          key: gradle
          path: |
            ~/.gradle/wrapper
            ~/.gradle/jdks
            ~/.gradle/caches
      - name: publish
        run: ${{ secrets.GRADLEW }} publish
